"""Corregir relación y claves foráneas

Revision ID: 044d36407ff9
Revises: 
Create Date: 2024-11-08 23:47:16.945022

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '044d36407ff9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conteos', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['codigoEAN'])
        batch_op.create_foreign_key(None, 'productos', ['codigoEAN'], ['codigoEAN'])

    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.alter_column('fecha',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)
        batch_op.alter_column('cliente',
               existing_type=mysql.VARCHAR(length=120),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('estado',
               existing_type=mysql.VARCHAR(length=1),
               type_=sa.String(length=10),
               existing_nullable=False,
               existing_server_default=sa.text("'A'"))
        batch_op.drop_index('fk_pedidos_productos_idx')
        batch_op.drop_index('ix_productos')
        batch_op.drop_constraint('fk_pedidos_productos', type_='foreignkey')
        batch_op.create_foreign_key(None, 'productos', ['idproducto'], ['idproducto'])
        batch_op.drop_column('diferencial')
        batch_op.drop_column('cantidad_contada')

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.alter_column('validacion',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.alter_column('validacion',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)

    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cantidad_contada', mysql.DECIMAL(precision=8, scale=2), server_default=sa.text("'0.00'"), nullable=True))
        batch_op.add_column(sa.Column('diferencial', mysql.DECIMAL(precision=8, scale=2), server_default=sa.text("'0.00'"), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_pedidos_productos', 'productos', ['idproducto'], ['idproducto'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_index('ix_productos', ['fecha', 'ruta', 'idcliente', 'idproducto'], unique=False)
        batch_op.create_index('fk_pedidos_productos_idx', ['idproducto'], unique=False)
        batch_op.alter_column('estado',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=1),
               existing_nullable=False,
               existing_server_default=sa.text("'A'"))
        batch_op.alter_column('cliente',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.alter_column('fecha',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=False)

    with op.batch_alter_table('conteos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
